baseURL                          = "https://bpkleer.de/"   # Your domain name. Must end with "/"
theme                            = "introduction"
DefaultContentLanguage           = "de"                    # Default language for multilingual sites
ignoreFiles                      = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
    themeStyle                   = "auto"                  # Choose "light" or "dark" or "auto"
    favicon                      = "/img/fav.ico"          # Path to favicon file
    showRSSButton                = false                   # Show rss button in navigation
    fadeIn                       = false                    # Turn on/off the fade-in effect
    fadeInIndex                  = false                   # Turn on/off the fade-in effect on the index page even if fade-in was otherwise turned off
    dateFormat                   = "Jan 2, 2006"

    # Configure the home page
    [params.home]
        introHeight              = "medium"            # Input either "medium" or "large" or "fullheight"
        showLatest               = true                    # Show latest blog post summary
        showAllPosts             = false                   # Set true to list all posts on home page, or set false to link to separate blog list page
        allPostsArchiveFormat    = true                    # show all posts in an archive format
        numberOfProjectsToShow   = 6                       # Maximum number of projects to show on home page. Unset or comment out to show all projects
        localTime                = true                    # Show your current local time in contact section
        timeZone                 = "Europe/Berlin" #"America/Recife"   # Your timezone as in the TZ* column of this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
        timeFormat               = "de"                 # Language specific format to use
    [params.projects]
        useTwoColumns            = false                   # Use a layout with two columns instead of three

    # Share buttons on blog post pages
    [params.share]
        twitter                  = false
        facebook                 = false
        pinterest                = false

    # Social icons appear in introduction and contact section. Add as many more as you like.
    # Icon pack "fab" includes social network icons, see: https://fontawesome.com/icons?d=gallery&s=brands&m=free
    # Icon pack "fas" includes solid style icons, see: https://fontawesome.com/icons?d=gallery&s=solid&m=free
    [[params.social]]
        url   = "https://de.linkedin.com/in/kleer"
        icon  = "linkedin-in fa-2x" # icon name without the 'fa-'
        icon_pack = "fab"
    [[params.social]]
        url   = "https://github.com/bpkleer"
        icon  = "github fa-2x" # icon name without the 'fa-'
        icon_pack = "fab"
    [[params.social]]
        url   = "https://orcid.org/0000-0003-1935-387X"
        icon  = "orcid ai-2x" # icon name without the 'fa-'
        icon_pack = "ai"
    [[params.social]]
        url   = "http://lattes.cnpq.br/4785970328498860"
        icon  = "lattes ai-2x" # icon name without the 'fa-'
        icon_pack = "ai"
    [[params.social]]
        url = "mailto:philipp.kleer@posteo.com"  # For a direct email link, use "mailto:test@example.org".
        icon = "paper-plane fa-2x" # icon name without the 'fa-'
        icon_pack = "fas"

# We only use tag as a taxonomies
# You can add more by yourself
[taxonomies]
  tag = "tags"
  series = "series"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    # For styles, see https://xyproto.github.io/splash/docs/longer/all.html
    style = "friendly"
    tabWidth = 4

[languages]
    [languages.en]
        languageName     = "English"
        languageCode     = "en-us"
        contentDir       = "content/en"
        weight           = 2
        title            = "Introduction"
        [languages.en.params]
            description  = "Personal website of Dr. Philipp Kleer"   # Max 160 characters show in search results
            footerText   = "&copy; Philipp Kleer, 2024."                      # Text to override default footer text (markdown allowed)

    [languages.de]
        languageName     = "Deutsch"
        languageCode     = "de"
        contentDir       = "content/de"
        weight           = 1
        title            = "Vorstellung"
        [languages.de.params]
            dateFormat   = "2. January 2006"
            description  = "Persönliche Website von Dr. Philipp Kleer"
            footerText   = "&copy; Philipp Kleer, 2024."
            
    [languages.pt]
        languageName     = "Português"
        languageCode     = "pt"
        contentDir       = "content/pt"
        weight           = 3
        title            = "Apresentação"
        [languages.pt.params]
            dateFormat   = "2. January 2006"
            description  = "Website do Dr. Philipp Kleer"
            footerText   = "&copy; Philipp Kleer, 2024."