---
title: "Fortbildungen"
weight: 14
---


#### Methodenfortbildungen
- 2023: Gesis Spring Seminar: *Comparative Social Research with Multi-Group SEM*
- 2021: ECPR Virtual Spring School in Methods and Techniques 2021, KU Leuven: *Introduction to Structural Equation Modelling*
- 2020: ECPR Virtual Summer School in Methods and Techniques 2020, CEU Budapest: *Quantitative Text Analysis*
- 2019: 48. Gesis Spring Seminar "Bayesian Modelling in the Social Sciences: *Introduction to Bayesian Models for the Social Sciences*
- 2018: ECPR Summer School in Methods and Techniques 2018, CEU Budapest: *Applied Multilevel Regression Modelling*
- 2016: 5. Gesis Summer School in Survey Methodology: *Introduction to Data Analysis Using R*

#### Didaktik-Fortbildungen
- 2020: Prüfungsrecht
- 2019: Konfliktkompetenz für den Hochschulalltag (I + II)
- 2017: Zertifikat Kompetenz für professionelle Hochschullehre (14 Workshops & 1 Lehrprojekt), u.a. *Einführung in die kollegiale Beratung*, *Diskussionen leiten* und *Studienberatung von nicht-traditionellen Studierenden*

#### Wissenschaftsmanagement-/verwaltung
- 2023: Drittmittel-Expert:innen Programm 2023
- 2022: ABC der Antragstellung
- 2020: SAP Schulung Beginner \& Fortgeschrittene
- 2019: Grundzüge des Berufungsverfahrens