---
title: "Aktivitäten"
weight: 15
bibliography: [../../../../static/files/cv.bib]
csl: [../../../../static/files/apa-cv.csl]
link-citations: false
suppress-bibliography: true
--- 

Während meiner akademischen Tätigkeiten habe ich neben **internationalen** Fachvorträgen und Fachveröffentlichungen auch öffentliche Vorträge gehalten, in denen ich Fachinhalte/-probleme einer breiteren Öffentlichkeit vorgestellt habe. Insbesondere konnte ich auf Konferenzen und Aufenthalten im Ausland meine **interpersonalen** und **kulturellen Kompetenzen** ausbauen. 

Eine Übersicht meines akademischen Werdegangs finden Sie auch in meinem **akademischen CV**: [**DE**](https://bpkleer.github.io/files/cvs-kleer-de.pdf).

#### Aktuelle Publikationen

[@Kleer2024a]

[@Kleer2024c]

[@Kleer2024e]

[@Junge2024]

[@Kleer2024b]

[@Hunklinger2024]

[@Abendschoen2023] 

[@Kleer2023]

[@Abendschoen2022a]

[@Kleer2021]

[@Kleer2020]

#### Auslandsaufenthalte

{{% visits %}}

#### Konferenzen

{{% conference %}}
<h6><sup>P</sup> Paper; <sup>C</sup> Chair</h6>

#### Gastvorträge

{{% talks %}}

#### Fördermittel
|   |   |
|:---:|---------------------------------|
| 2024 | Kongressreisen-Stipendium (DAAD), European Conference on Gender and Politics, ECPR Standing Group *Gender and Politics* (Gent, Belgium, Fördersumme: 907 Euro) |
|2023   |  Kongressreisen-Stipendium (DAAD), World Congress der International Political Science Association (IPSA, Buenos Aires, Argentinien; Fördersumme: 2,440 Euro) |  
| 2021  | Statistik+: Einstieg in R leichtgemacht!, gemeinsam mit Simone Abendschön, QSL-D, Fachbereich 03, Justus-Liebig-Universität Gießen (Fördersumme: 20.754 Euro)  |
|2020|  Kongressreisen-Stipendium (DAAD), World Congress des International Council of Central Eastern Europe Studies (Concordia University Montréal (Fördersumme: 1.916 Euro; nicht angetreten Covid-19-Pandemie) |   
| 2018 |Individuelle Studierendenentwicklung fördern: Einführung eines Web-Based- Trainings zur Verbesserung der Methodenkompetenz, gemeinsam mit Simone Abendschön, QSL-D, Fachbereich 03, Justus-Liebig-Universität Gießen (Fördersumme: 23.960 Euro)|

