---
title: "Pesquisa"
weight: 13
bibliography: [../../../../static/files/cv.bib]
csl: [../../../../static/files/apa-cv.csl]
link-citations: false
suppress-bibliography: true
---

Meus interesses de pesquisa estão tanto na socialização política quanto nas atitudes políticas e na pesquisa de apoio político. Abaixo, você encontra uma visão geral dos meus projetos de pesquisa.

Em projetos de pesquisa menores e maiores, pude desenvolver minhas habilidades em **planejamento** e **organização e gestão de projetos** e descobrir e consolidar minha força em **colaboração em equipe**. Além disso, consegui expandir constantemente minhas habilidades em **aplicação** e **análise de dados quantitativos**.

Um dos meus pontos fortes está na **compreensão** de grandes quantidades de **informação**, uma habilidade crucial em meus esforços de pesquisa. Sou especialista em destilar **informações complexas** em **insights significativos**, permitindo uma compreensão mais profunda dos tópicos abordados.

Mais detalhes poderia ser encontrado no meu **currículo academico**: [**PT**](https://bpkleer.github.io/files/cvs-kleer-br.pdf).

#### Socialização política
No campo da pesquisa sobre socialização política, estou particularmente preocupado com os jovens e com os professores e professores estudantes como importantes agentes de socialização. No caso dos jovens, o foco está nos fatores que influenciam o desenvolvimento do interesse político e o uso da mídia política. No contexto dos agentes de socialização, concentro-me especialmente nas atitudes latentes no sentido de uma sala de aula democrática e nas habilidades de informação política dos professores estudantes.

Atualmente, estou trabalhando no projeto [**G-EPIC**](https://www.g-epic.eu) (EU-Horizon), no qual processo principalmente o conhecimento e analiso os dados para investigar os efeitos (interseccionais) sobre o interesse político e a autoeficácia política dos jovens.


##### Publicações selecionadas sobre esse tópico:

[@Kleer2024a]

[@Kleer2024c]

[@Kleer2024e]

[@Kleer2023a]

[@Abendschoen2023]

[@Abendschoen2022a]

[@Kleer2021]


#### Atitudines poliíticas / Apoio político
Juntamente com Michael Hunklinger, estou trabalhando nos efeitos sobre o comportamento de voto de pessoas LGBTIQ\*. Em particular, estamos investigando até que ponto as atitudes específicas do grupo têm um impacto sobre as decisões de voto e o comportamento de participação. 

Em minha tese de doutorado, analisei intensamente as condições teóricas dos diferentes níveis de apoio político no contexto de democracias consolidadas na Europa Central e Oriental no campo da pesquisa de apoio político e examinei essas possíveis interações, levando em conta os efeitos econômicos.


##### Publicações selecionadas sobre esse tópico:

[@Junge2024]

[@Kleer2024b]

[@Hunklinger2024]

[@Kleer2023]

[@Kleer2024b]