---
title: "Atividades anteriores de ensino/pesquisa"
weight: 13
bibliography: [../../../../static/files/cv.bib]
csl: [../../../../static/files/apa-cv.csl]
link-citations: false
suppress-bibliography: true
---

## Ensino

Em minhas funções acadêmicas anteriores na área de métodos quantitativos, desenvolvi ensino prático em pesquisa social empírica para o curso de graduação *Ciências Sociais*. Meu compromisso com a educação se reflete na formação e orientação de estudantes, especialmente em trabalhos de conclusão de curso, onde eu **apresento conteúdos complexos de forma compreensível** e ofereço **feedback construtivo**.

Desenvolvi vários treinamentos baseados na web e, como líder de projeto, fui responsável pelo planejamento, implementação e controle desses projetos de ensino. Um foco especial foi a integração de R e Git em cursos aplicados, a fim de ensinar os alunos a utilizar ferramentas de projeto e colaboração e possibilitar a verificação automatizada de submissões de código.

Além disso, criei vídeos de aprendizado sobre estatística e R para a Justus-Liebig-Universität Gießen e a FernUniversität Hagen, com o objetivo de promover a aplicação prática de métodos estatísticos.

### Publicações na área de ensino:

[@Kleer2024f]

[@Kleer2020]

#### Link para os projetos de ensinar

- Web-Based-Training *Estatística para ciências socias* (alemão): [ao vivo](https://uni-giessen.de/methoden-ifp-stats101), [git-Repository](https://gitlab.ub.uni-giessen.de/methoden-politik/einstieg-in-statistik)

- Web-Based-Training *Facilitar a entrada em R* (alemão): [ao vivo](https://uni-giessen.de/methoden-ifp-r), [git-Repository](https://gitlab.ub.uni-giessen.de/methoden-politik/einstieg-in-r)

- Web-Based-Training *Introdução em SPSS* (alemão): [ao vivo](https://uni-giessen.de/methoden-ifp-spss), [git-Repository](https://gitlab.ub.uni-giessen.de/methoden-politik/einstieg-in-spss)

- Workshop *Daten bändigen & visualisieren mit R*: [git-Repository](https://gitlab.com/bpkleer/tidyverse-course)

- CI no ensino com R (inglês): [git-Repository](https://gitlab.com/bpkleer/ci-cd-teaching)

- Lernvideos *Introdução em R* (alemão, FU Hagen): [Vimeo](https://youtube.com/playlist?list=PL30dYVYYotm_19tT4z3bDcxlzgZzR4Gzp&si=8m2iUi5nun2w54gV)
 
- Vídeos da aula *Introdução à Estatística* (alemão): [Vimeo](https://www.youtube.com/playlist?list=PL30dYVYYotm9kvGnrAwp-F6mFnZhAOdlK)


#### Cursos anteriores (seleção) 
Aqui você encontra uma visão geral dos cursos que ensinei até agora. Os cursos sempre foram realizados no idioma do título.

{{% lehre %}}

## Pesquisa
Meus interesses de pesquisa estão na socialização política, bem como na pesquisa sobre atitudes e apoio político. Nesse contexto, desenvolvi minhas habilidades em **planejamento** e **organização de projetos de pesquisa** e solidifiquei minhas forças em **colaboração em equipe**. Adquiri competências abrangentes na **aplicação** e **análise (de dados quantitativos complexos)**, o que me permite destilar informações complexas em **insights significativos**.

Uma visão geral da minha trajetória acadêmica pode ser encontrada no [Orcid](https://orcid.org/0000-0003-1935-387X) ou [Lattes](http://lattes.cnpq.br/4785970328498860).

##### Publicações selecionadas:

[@Kleer2024a]

[@Kleer2024c]

[@Kleer2024d]

[@Kleer2024e]

[@Hunklinger2024]

[@Kleer2023]

[@Kleer2023a]

[@Abendschoen2023]

[@Abendschoen2022a]

[@Kleer2021]


## Outros
Durante minhas atividades acadêmicas, não só dei palestras e publicações **internacionais** , mas também dei palestras públicas nas quais apresentei conteúdo científico/problemas científicas a um público mais amplo. Em particular, pude expandir minhas competências **interpessoais** e **culturais** em conferências e estadias no exterior. 

#### Estadia no exterior 
{{% visits %}}

#### Conferências

{{% conference %}}
<h6><sup>A</sup> Artigo/Apresentação; <sup>C</sup> Chair no painel</h6>

#### Palestras de convidados

{{% talks %}}
