---
title: "Atividades"
weight: 15
bibliography: [../../../../static/files/cv.bib]
csl: [../../../../static/files/apa-cv.csl]
link-citations: false
suppress-bibliography: true
--- 

Durante minhas atividades acadêmicas, não só dei palestras e publicações **internacionais** , mas também dei palestras públicas nas quais apresentei conteúdo científico/problemas científicas a um público mais amplo. Em particular, pude expandir minhas competências **interpessoais** e **culturais** em conferências e estadias no exterior. 

Mais detalhes poderia ser encontrado no meu **currículo academico**: [**PT**](https://bpkleer.github.io/files/kleer-cvs-pt.pdf).

#### Publicações atuais
[@Hunklinger2024]

[@Abendschoen2023] 

[@Kleer2023]

[@Abendschoen2022a]

[@Kleer2021]

[@Kleer2020]

#### Estadia no exterior 
{{% visits %}}

#### Conferências

{{% conference %}}
<h6><sup>A</sup> Artigo/Apresentação; <sup>C</sup> Chair no painel</h6>

#### Palestras de convidados

{{% talks %}}

#### Bolsas
|   |   |
|:---:|---------------------------------|
| 2024 | Bolsa de viagem (DAAD), European Conference on Gender and Politics, ECPR Standing Group *Gender and Politics* (Gent, Bélgica, valor da bolsa: 907 Euro) |
| 2023 |  Bolsa de viagem (DAAD), Congresso Mundial da Associação Internacional de Ciência Política em Buenos Aires, Argentina (valor da bolsa: 2.440 euros) | 
| 2021 | Statistics+: Easy start in R, junto com Simone Abendschön, Teaching Innovation Grant (QSL-D), Faculdade 03, Justus-Liebig-University Giessen (valor do financiamento: 20.754 euros) |
| 2020 | Bolsa de viagem (DAAD), Congresso Mundial do Conselho Internacional de Estudos da Europa Centro-Oriental na Concordia University Montréal (valor da bolsa: 1.916 euros; cancelado devido à pandemia de Covid-19) |
| 2018 | Fomentar a competência metodológica dos alunos individualmente: Implementation of a web-based-training in MA courses, juntamente com Simone Abendschön, Teaching Innovation Grant (QSL-D), Faculty 03, Justus-Liebig-University Giessen (valor do financiamento: 23.960 euros) | 