---
title: "Academia"
weight: 15
bibliography: [../../../../static/files/cv.bib]
csl: [../../../../static/files/apa-cv.csl]
link-citations: false
suppress-bibliography: true
--- 

During my academic activities, I have given **international** scientific presentations, as well as public lectures in which I presented scientific content/problems to a wider audience. Furthermore, I published part of my work internationaly. In particular, I expanded my **interpersonal** and **cultural skills** at conferences and stays abroad.

At the Chair of Methods in Political Science, I was involved to a large extent in the organization of the professorship and the coordination of student assistants.

You can find a more comprehensive overview in my [**academic CV**](https://bpkleer.github.io/files/kleer-cvs-en.pdf).

#### Stays abroad
{{% visits %}}

#### Conferences

{{% conference %}}
<h6><sup>P</sup> Paper; <sup>C</sup> Chair</h6>

#### Talks

{{% talks %}}

#### Recent publications
[@Hunklinger2024]

[@Abendschoen2023] 

[@Kleer2023]

[@Abendschoen2022a]

[@Kleer2021]

[@Kleer2020]

#### Grants
| | |
|:---:|---------------------------------|
| 2024 | Travel-Grant (DAAD), European Conference on Gender and Politics, ECPR Standing Group *Gender and Politics* (Gent, Belgium, grant amount: 907 Euro) |
| 2023 | Travel-Grant (DAAD), World Congress of International Political Science Association in Buenos Aires, Argentina (grant amount: 2,440 Euro) |
| 2021 | Statistics+: Easy start in R, together with Simone Abendschön, Teaching Innovation Grant (QSL-D), Faculty 03, Justus-Liebig-University Giessen (funding amount: 20,754 Euro) |
| 2020 | Travel-Grant (DAAD), World Congress of the International Council of Central Eastern Europe Studies at Concordia University Montréal (grant amount: 1,916 Euro; cancelled due to Covid-19-pandemic) |
| 2018 | Fostering students’ methods competence individually: Implementation of a web-based-training in MA courses, together with Simone Abendschön, Teaching Innovation Grant (QSL-D), Faculty 03, Justus-Liebig-University Giessen (funding amount: 23,960 Euro) |
