---
title: "Lehre"
weight: 12
bibliography: [../../../../static/files/cv.bib]
csl: [../../../../static/files/apa-cv.csl]
link-citations: false
suppress-bibliography: true
---

Während meiner Zeit als wissenschaftlicher Mitarbeiter an der Professur für Methoden der Politikwissenschaft habe ich kontinuierlich in den Studiengängen des Instituts gelehrt, wobei ein Fokus meiner Lehre in der praktischen Vermittlung empirischer Sozialforschung im BA-Studiengang *Social Sciences* lag.

Mein Interesse für Bildung spiegelt sich in meiner Erfahrung in der Schulung und Betreuung von Studenten (z.B. bei Abschlussarbeiten) wider. Meine Lehrrollen haben mich mit der Fähigkeit ausgestattet, **Wissen effektiv** zu vermitteln, **komplexe Inhalte** aufzubereiten und effektiv zu präsentieren sowie **Diskussionen** anzuleiten und **konstruktives Feedback** zu geben, um das Lernen zu erleichtern.

In der Lehre habe ich stets Kurse weiterentwickelt und mehrere Web-Based-Trainings als größere **Lehrprojekte konzipiert, entwickelt und umgesetzt**. In diesen Projekten habe ich als **Projektleitung** die Planung und Umsetzung entwickelt sowie kontrolliert und **studentische Hilfskräfte im Projekt geführt**. 

Daneben habe ich für die Justus-Liebig-Universität Gießen als auch für die FernUniversität Hagen im Laufe der letzten Jahre mehrere **Lernvideos** rund um Statistik und die Anwendung in R erstellt.

In **anwendungsorientierten** Kursen habe ich dabei immer Wert darauf gelegt, **Projekt-/Kollaborationstools** (wie Git) zu integrieren, und zum Beispiel **automatisierte Kontrollen von Code-Abgaben** über Git zu ermöglichen (siehe CI-Projekt unten). 

#### Veröffentlichungen in Lehre

[@Kleer2024f]

[@Kleer2020]

#### Links Lehrprojekten

- Web-Based-Training *Statistik für Sozialwissenschaften*: [Live-View](https://uni-giessen.de/methoden-ifp-stats101), [git-Repository](https://gitlab.ub.uni-giessen.de/methoden-politik/einstieg-in-statistik)

- Web-Based-Training *Einstieg in R*: [Live-View](https://uni-giessen.de/methoden-ifp-r), [git-Repository](https://gitlab.ub.uni-giessen.de/methoden-politik/einstieg-in-r)

- Web-Based-Training *Einstieg in SPSS*: [Live-View](https://uni-giessen.de/methoden-ifp-spss), [git-Repository](https://gitlab.ub.uni-giessen.de/methoden-politik/einstieg-in-spss)

- Workshop *Daten bändigen & visualisieren mit R*: [git-Repository](https://gitlab.com/bpkleer/tidyverse-course)

- Anwendung *CI in der Lehre mit R*: [git-Repository](https://gitlab.com/bpkleer/ci-cd-teaching)

- Lernvideos rund um R (für die FU Hagen): [Vimeo](https://vimeo.com/channels/1815333)

- Lernvideos zu Vorlesungen Statistik für die Sozialwissenschaften: [Vimeo](https://vimeo.com/channels/1815335)


#### Übersicht bisheriger Kurse
Hier finden Sie eine Übersicht an Kursen und Workshops, die ich bisher gegeben habe. Die Kurse haben immer in Titelsprache stattgefunden.

{{% lehre %}} 